apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: my-namespace
  labels:
    run: microservice  
spec:
  replicas: 1
  selector:
    matchLabels:
      run: microservice
  template:
    metadata:
      labels:
        run: microservice
    spec:
      containers:
      - name: microservice
        image: ${REPOSITORY_TAG}
        ports:
        - containerPort: 80        
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 250Mi
            cpu: 80m
