apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: my-namespace
  labels:
    run: microservice
spec:
  selector:
    run: microservice
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30002
  type: NodePort

